### ISSUE TITLE
Issues with ACE3 when profiler is loaded in combination with CUP Vehicles

### ISSUE THREAD

**Issue by Auge103** [dedmen/ArmaScriptProfiler#11]
Somehow ACE3 completely stops working when the profiler mod is loaded in combination with CUP Vehicles. Unloading only CUP Vehicles or the profiler mod makes it work again.

-> Complete list of loaded mods (all latest steam versions):
`Arma 3 profiling branch`
`CBA`
`ACE / ACEX`
`This profiler`
`CUP Units / Weapons / Vehicles`
(Doesn't matter if the ACE compat for CUP is loaded or not)

When I try to load the ACE inventory in the main menu, my log show this:
```
[1122,48.78,0,"XEH: PreInit started. v3.9.1.181229"]
10:10:33 [1122,49.154,0,"CBA CACHE DISABLED? (Disable caching with cba_cache_disable.pbo):  _compileType=compile"]
```
and starts spamming these:
```
"TestUser/BIS_fnc_log: [preInit] ""DeltaTime computation started"""
[XEH]: preInit already executed. Abort preInit.
Attempt to override final function - bis_fnc_missionflow
Attempt to override final function - bis_fnc_storeparamsvalues_data
```
and then never finishes loading. When connecting to a server, almost every aspect of ACE is missing or not working, even the settings menu is completely invisible (buttons are missing, but space for them is used)
Any idea what is going on here?

**Comment by dedmen** [comment]
Which version of the profiler exactly? The Tracy variant? Can you upload full RPT?

**Comment by Auge103** [comment]
This version:
https://github.com/dedmen/ArmaScriptProfiler/releases/tag/1.1.30
Also tried this with the "stable" release of A3, same result, here's the rpt:
[log.zip](https://github.com/dedmen/ArmaScriptProfiler/files/2845059/log.zip)
File ends when I closed A3 via the "nonresponsive" window.

**Comment by dedmen** [comment]
Please try if it still happens with the latest release.

**Comment by Auge103** [comment]
Nice, its working! And this release even fixed another `0x0000005 status_access_violation` error when starting arma as profiling branch in combination with this mod. Thanks a lot!
