### ISSUE TITLE
Intercept core not found.

### ISSUE THREAD

**Issue by BrightCandle** [dedmen/ArmaScriptProfiler#16]
Adding the mod to the modlist in swifty I am getting the following start error message:

Addon 'dedmen_script_profiler' requires addon 'intercept_core'

Stated version on releases is  1.5.37 "Network Profiler"

Zip appears not to contain intercept_core.pbo anymore.

**Comment by dedmen** [comment]
Intercept is a required mod.
https://steamcommunity.com/sharedfiles/filedetails/?id=1645973522
