### ISSUE TITLE
Persist session to tracy file while it is running

### ISSUE THREAD

**Issue by mwpowellhtx** [dedmen/ArmaScriptProfiler#21]
I am trying to troubleshoot an issue with Arma 3 black screen freezing. I am able to force Arma 3 to quit with an always in front task manager, so at least that is good. However, when that happens, it also pulls tracy down with it. The freeze is not tracy related, it is happening anyway, but the fact that it pulls tracy down with it is not good, and I lose the recorded data. Is it possible that I can tell tracy to record to file while the session is alive? That would be helpful. Maybe there's an option that allows for this already, I do not know. Thanks!

**Comment by dedmen** [comment]
There is Tracy capture.exe that does exactly that, writes directly to file.

**Comment by mwpowellhtx** [comment]
Okay... Not sure what that means; I run `tracy`? How do I make sure `capture` is in the loop and saving results when this scenario occurs?
