### ISSUE TITLE
Report IP addresses ports etc to logs

### ISSUE THREAD

**Issue by mwpowellhtx** [dedmen/ArmaScriptProfiler#22]
It would be helpful to know that instead of wondering where to direct either `tracy` or `capture`. `capture`, in particular, just sits there waiting for `loopback:8086` to connect, i.e.

```
Connecting to 127.0.0.1:8086...
```

And that is all I ever see. Which port should it be connecting to?

**Comment by dedmen** [comment]
Its always port 8086 (the default for tracy, which I have no control over).
Which is also the default for capture and the UI.
No need for a log message that tells you a default value that all the tools that can interact with it already know.
