### ISSUE TITLE
With compileScript the profiler doesn't work correctly anymore

### ISSUE THREAD

**Issue by Xeno69** [dedmen/ArmaScriptProfiler#24]
With the introduction of compileScript in 2.04 for functions the script profiler doesn't work anymore.

Tracy only shows unknown scripts for functions compiled with compileScript:

![image](https://user-images.githubusercontent.com/3141271/115735609-e7850180-a38a-11eb-9830-e7c96ce41636.png)

Would be nice if you find time to fix it :)

**Comment by dedmen** [comment]
I updated profiler for compileScript.
But don't know if you have that already, or if I didn't publish it

**Comment by Xeno69** [comment]
I think you haven't published it yet. At least that's what you said some time ago.

**Comment by Xeno69** [comment]
Script paths are shown again, function names (first column) are missing. For me the problem is solved.
