### ISSUE TITLE
A3 2.12+ crashing

### ISSUE THREAD

**Issue by mwpowellhtx** [dedmen/ArmaScriptProfiler#28]
Trying to load in with _Arma Script Profiler_ and _Intercept_, crashing with DBZ errors. Does it need updating for the latest A3 version?

**Comment by mwpowellhtx** [comment]
I'm confused, the latest documented release is _Tracy has been updated to 0.6.0_. And yet `tracy.exe` reports:

![image](https://user-images.githubusercontent.com/1824187/223199988-88c28370-3b4d-4a03-9518-6c992df15faa.png)

Still, I'll start with the wiki guidance, disable BE and so on...

**Comment by mwpowellhtx** [comment]
Not a BE issue, tried running with `-NoBattlEye` command line args, no difference. Not even getting to an A3 splash screen.

Loaded both _Intercept Minimal Dev_ and _Arma Script Profiler_, getting the following:

![image](https://user-images.githubusercontent.com/1824187/223204004-f64a676c-f709-44c4-ba83-e835f88659e7.png)

The last meaningful log entry prior to DBZ crash dump:

```
13:27:36 "Intercept: Load completed [SQF-Assembly]"
13:27:36 Intercept Loading Plugin: ArmaScriptProfiler
```

**Comment by mwpowellhtx** [comment]
Is anyone using this at all? Given that it is crashing, I don't know. And with the dirth of adequate versioning at all levels throughout the deployed files, difficult to say in which versions there is an issue. As stated here and in other formats, I'd like to be more helpful, because with a thing like this, `tracy`, etc, it is pretty useful at debugging certain scenarios. Anyhow, y'all know how/where I stand on this if you need/want the help.

**Comment by dedmen** [comment]
I closed this because i fixed the crash

**Comment by mwpowellhtx** [comment]
Sweet, thanks.
